name: &name "QuartzNet5x1Aug"

model:
  sample_rate: &sample_rate 16000
  repeat: &repeat 1
  dropout: &dropout 0.0
  separable: &separable true
  labels: &labels ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "*"]
  use_cer: true


  train_ds:
    manifest_filepath: <path_to>/train_manifest.json
    sample_rate: 16000
    labels: *labels
    batch_size: 256
    num_workers: 12
    trim_silence: False
    max_duration: 3.83
    shuffle: True
    is_tarred: False
    tarred_audio_filepaths: null
    tarred_shard_strategy: "scatter"
    augmentor:
      white_noise:
            prob: 0.1
            min_level: -50
            max_level: -10
      impulse:
            prob: 0.2
            manifest_path: <path_to>/impulse_manifest.json
      speed:
            prob: 0.15
            min_speed_rate: 0.8
            max_speed_rate: 1.2
            num_rates: 5
            sr: 16000
            resample_type: 'kaiser_fast'
      gain:
            prob: 0.1
            min_gain_dbfs: -10
            max_gain_dbfs: 10
      noise:
            prob: 0.2
            manifest_path: <path_to>/noises_manifest.json
            orig_sr: 16000
            min_snr_db: 10
            max_snr_db: 50
      transcode_aug:
            prob: 0.1

  validation_ds:
    manifest_filepath: <path_to>/validation_manifest.json
    sample_rate: 16000
    labels: *labels
    batch_size: 32
    shuffle: False
    augmentor:
      white_noise:
            prob: 0.1
            min_level: -50
            max_level: -10
      impulse:
            prob: 0.2
            manifest_path: <path_to>/impulse_manifest.json
      speed:
            prob: 0.15
            min_speed_rate: 0.8
            max_speed_rate: 1.2
            num_rates: 5
            sr: 16000
            resample_type: 'kaiser_fast'
      gain:
            prob: 0.1
            min_gain_dbfs: -10
            max_gain_dbfs: 10
      noise:
            prob: 0.2
            manifest_path: <path_to>/noises_manifest.json
            orig_sr: 16000
            min_snr_db: 10
            max_snr_db: 50
      transcode_aug:
            prob: 0.1

  test_ds:
    manifest_filepath: <path_to>/test_manifest.json
    sample_rate: 16000
    labels: *labels
    batch_size: 32
    shuffle: False
    augmentor:
      white_noise:
            prob: 0.1
            min_level: -50
            max_level: -10
      impulse:
            prob: 0.2
            manifest_path: <path_to>/rirs_manifest.json
      speed:
            prob: 0.15
            min_speed_rate: 0.8
            max_speed_rate: 1.2
            num_rates: 5
            sr: 16000
            resample_type: 'kaiser_fast'
      gain:
            prob: 0.1
            min_gain_dbfs: -10
            max_gain_dbfs: 10
      noise:
            prob: 0.2
            manifest_path: <path_to>/noises_manifest.json
            orig_sr: 16000
            min_snr_db: 10
            max_snr_db: 50
      transcode_aug:
            prob: 0.1

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: "per_feature"
    window_size: 0.02
    sample_rate: *sample_rate
    window_stride: 0.01
    window: "hann"
    features: &n_mels 64
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001

  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    rect_freq: 50
    rect_masks: 5
    rect_time: 120

  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    feat_in: *n_mels
    activation: relu
    conv_mask: true

    jasper:
    - dilation: [1]
      dropout: *dropout
      filters: 256
      kernel: [33]
      repeat: 1
      residual: false
      separable: *separable
      stride: [2]

    - dilation: [1]
      dropout: *dropout
      filters: 256
      kernel: [39]
      repeat: *repeat
      residual: true
      separable: *separable
      stride: [1]

    - dilation: [1]
      dropout: *dropout
      filters: 336
      kernel: [51]
      repeat: *repeat
      residual: true
      separable: *separable
      stride: [1]

    - dilation: [1]
      dropout: *dropout
      filters: 512
      kernel: [63]
      repeat: *repeat
      residual: true
      separable: *separable
      stride: [1]

    - dilation: [1]
      dropout: *dropout
      filters: 512
      kernel: [75]
      repeat: *repeat
      residual: true
      separable: *separable
      stride: [1]

    - dilation: [2]
      dropout: *dropout
      filters: 512
      kernel: [87]
      repeat: 1
      residual: false
      separable: *separable
      stride: [1]

    - dilation: [1]
      dropout: *dropout
      filters: &enc_filters 768
      kernel: [1]
      repeat: 1
      residual: false
      stride: [1]

  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: *enc_filters
    num_classes: 11
    vocabulary: *labels

  optim:
    name: novograd
    # _target_: nemo.core.optim.optimizers.Novograd
    lr: .01
    # optimizer arguments
    betas: [0.8, 0.5]
    weight_decay: 0.001

    # scheduler setup
    sched:
      name: CosineAnnealing

      # pytorch lightning args
      # monitor: val_loss
      # reduce_on_plateau: false

      # Scheduler params
      warmup_steps: null
      warmup_ratio: null
      min_lr: 0.00003
      last_epoch: -1

trainer:
  gpus: 1 # number of gpus
  max_epochs: 20
  max_steps: null # computed at runtime if not set
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  log_every_n_steps: 1  # Interval of logging.
  val_check_interval: 1.0  # Set to 0.25 to check 4 times per epoch, or an int for number of iterations

exp_manager:
  exp_dir: <path_to_exps>/quartznet_5x1_aug
  name: *name
  create_tensorboard_logger: True
  create_checkpoint_callback: True
  # checkpoint_callback_params:
  #   monitor: "val_cer"
  #   mode: "min"
  create_wandb_logger: False
  # wandb_logger_kwargs:
  #   name: null
  #   project: null

hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null
